### ISSUE TITLE
png support is slightly brain dead.

### ISSUE THREAD

**Issue by ve7it** [ted051/Analyzer_EU1KY_CEC_AKF#1]
Lawrence Glaister VE7IT
19 Oct 2020

Of note:

png file support is brain damaged... the render engine draws images with an extra pixel/line causing the images to be slanted at about 30 degrees from vertical. This is probably an "off by one error", but I have not spotted where the problem is yet. Using .bmp files works fine.  To test this, make a 480x272 png file and call it logo.png. If this is placed in /AA/logo.png on the compact flash card, the image will be displayed when the analyser powers on. You will see the image is distorted. If you happen to resize the splash image to 479x272, it will render correctly.  The problem also exists when viewing previously stored screen shots.

Photo of bad render:
![P1010027](https://user-images.githubusercontent.com/784890/96545006-78541680-125c-11eb-96ee-645141cd01f6.JPG)

Actual 480x272 png image of what it is supposed to look like:
![logo](https://user-images.githubusercontent.com/784890/96545059-899d2300-125c-11eb-9e48-7cad7590255a.png)

Use .bmp file format for /AA/logo.bmp and set bmp as the option for screen saves in the configuration option.

If you make a custom logo.bmp in gimp, make the file size 480x272 or smaller.
When you export as a .bmp, under compatibility options, you must check the
"Do not write color space information" option. Under advanced options 24 bit color works.

**Comment by ted051** [comment]
Resolved
