### ISSUE TITLE
RF generator screen...

### ISSUE THREAD

**Issue by ve7it** [ted051/Analyzer_EU1KY_CEC_AKF#4]
I am working with the latest RF generator screen. It appears when entering the RF generator screen, a frequency is displayed, but there is no output until one presses on of the up or down frequency buttons.
There is a second oddity as well. When the FM or AM buttons are pressed and the rf output is on, one gets the modulation, but pressing the FM or AM buttons again shuts off the rf output. Another press, toggles the output on for about 1/2 seconds and then off again. The generator is mostly working, but definitely has some issues which can be detected by listening to the output in a receiver.
cheers
Lawrence

**Comment by ted051** [comment]
Because I was focused at the S21 screen, I did not test the modifications, sorry. 
Please be patient, next days the problems will be solved.
Wolfgang

**Comment by ted051** [comment]
I hope, this problem is now solved.

**Comment by ted051** [comment]
Problem solved
