### ISSUE TITLE
F7Discovery.depend and F7Discovery.elay

### ISSUE THREAD

**Issue by horga83** [ted051/Analyzer_EU1KY_CEC_AKF#5]
Would you please consider adding these two files to your .gitignore file.  I am trying to follow your github page but everytime I merge it updates my *.depend and *.elay file with yours.  Also remove it from the project repository.  This messes up my Embits IDE settings.

**Comment by ted051** [comment]
Hi, "horga83",
I have done, what you wanted. Thanks for your information.
Wolfgang

**Comment by horga83** [comment]
Looks like your F7Discovery.depend and .elay are still being updated.  Maybe you need to explicitly name them and remove the files from the github repo, you can keep your local copy.

**Comment by ted051** [comment]
I did so. Thank you for the hint.
